Additional options
udx-actions/ghost-inspector pull request #12
Opened 2024-01-23 23:27 UTC by mrkind

Add the possibility to add as many parameters to the request as needed.

2024-01-23 23:41 UTC, planv approved these changes

2024-01-23 23:45 UTC, planv requested changes
please update version as well

2024-01-24 09:49 UTC, kavaribes approved these changes

2024-01-24 14:41 UTC, planv approved these changes

2024-01-30 16:30 UTC, merged